export async function initializeProduct() {
  // Map code to id for categories
  const categories = await prisma.category.findMany();
  const codeToId: Record<string, bigint> = {};
  for (const cat of categories) {
    codeToId[cat.code] = cat.id;
  }

  const defaultProducts = [
    {
      name: 'Cafe Đen',
      categoryCode: 'cafe_viet',
      image: 'https://oola.vn/wp-content/uploads/2023/03/ca-phe-den.jpg',
      price: 25000,
      discountPercent: 5,
      description: 'Cafe đen Việt Nam thơm ngon, đậm vị, rang xay truyền thống.',
      rating: 4.8,
      reviews: 245,
      isBestSeller: false,
      isActive: true,
    },
    {
      name: 'Cafe Sữa Đá',
      categoryCode: 'cafe_viet',
      image: 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=400&h=300&fit=crop',
      price: 30000,
      discountPercent: 10,
      description: 'Cafe sữa đá truyền thống, vị ngọt ngào hài hòa.',
      rating: 4.9,
      reviews: 189,
      isBestSeller: false,
      isActive: true,
    },
    {
      name: 'Cafe Nâu',
      categoryCode: 'cafe_viet',
      image: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=400&h=300&fit=crop',
      price: 28000,
      discountPercent: 8,
      description: 'Cafe nâu đậm đà, pha chế theo phong cách Sài Gòn.',
      rating: 4.6,
      reviews: 178,
      isBestSeller: false,
      isActive: true,
    },
    {
      name: 'Bạc Xỉu',
      categoryCode: 'cafe_viet',
      image: 'https://images.unsplash.com/photo-1447933601403-0c6688de566e?w=400&h=300&fit=crop',
      price: 32000,
      discountPercent: 6,
      description: 'Bạc xỉu ngọt ngào, nhiều sữa đặc thơm béo.',
      rating: 4.7,
      reviews: 203,
      isBestSeller: false,
      isActive: true,
    },
    {
      name: 'Espresso',
      categoryCode: 'cafe_may',
      image: 'https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?w=400&h=300&fit=crop',
      price: 35000,
      discountPercent: 5,
      description: 'Espresso nguyên chất, đậm đà phong cách Ý.',
      rating: 4.5,
      reviews: 156,
      isBestSeller: false,
      isActive: true,
    },
    {
      name: 'Cappuccino',
      categoryCode: 'cafe_may',
      image: 'https://images.unsplash.com/photo-1572442388796-11668a67e53d?w=400&h=300&fit=crop',
      price: 45000,
      discountPercent: 8,
      description: 'Cappuccino Ý đậm đà với lớp foam mịn màng.',
      rating: 4.7,
      reviews: 234,
      isBestSeller: false,
      isActive: true,
    },
    {
      name: 'Latte',
      categoryCode: 'cafe_may',
      image: 'https://images.unsplash.com/photo-1561047029-3000c68339ca?w=400&h=300&fit=crop',
      price: 50000,
      discountPercent: 12,
      description: 'Latte thơm ngon với lớp sữa mịn màng.',
      rating: 4.6,
      reviews: 324,
      isBestSeller: false,
      isActive: true,
    },
    {
      name: 'Americano',
      categoryCode: 'cafe_may',
      image: 'https://images.unsplash.com/photo-1507133750040-4a8f57021571?w=400&h=300&fit=crop',
      price: 38000,
      discountPercent: 7,
      description: 'Americano nhẹ nhàng, phù hợp cho buổi sáng.',
      rating: 4.4,
      reviews: 189,
      isBestSeller: false,
      isActive: true,
    },
    {
      name: 'Macchiato',
      categoryCode: 'cafe_may',
      image: 'https://images.unsplash.com/photo-1485808191679-5f86510681a2?w=400&h=300&fit=crop',
      price: 52000,
      discountPercent: 10,
      description: 'Macchiato đặc biệt với chút caramel thơm ngon.',
      rating: 4.8,
      reviews: 267,
      isBestSeller: false,
      isActive: true,
    },
    {
      name: 'Frappuccino',
      categoryCode: 'cafe_da_xay',
      image: 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=400&h=300&fit=crop',
      price: 55000,
      discountPercent: 15,
      description: 'Cafe đá xay mát lạnh, thích hợp cho ngày hè.',
      rating: 4.5,
      reviews: 298,
      isBestSeller: false,
      isActive: true,
    },
    {
      name: 'Iced Coffee Blend',
      categoryCode: 'cafe_da_xay',
      image: 'https://images.unsplash.com/photo-1517701604599-bb29b565090c?w=400&h=300&fit=crop',
      price: 48000,
      discountPercent: 8,
      description: 'Cafe đá xay pha trộn với kem tươi thơm béo.',
      rating: 4.3,
      reviews: 176,
      isBestSeller: false,
      isActive: true,
    },
    {
      name: 'Mocha Frappe',
      categoryCode: 'cafe_da_xay',
      image: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400&h=300&fit=crop',
      price: 58000,
      discountPercent: 12,
      description: 'Mocha đá xay với chocolate đậm đà.',
      rating: 4.7,
      reviews: 245,
      isBestSeller: false,
      isActive: true,
    },
    {
      name: 'Trà Đào Cam Sả',
      categoryCode: 'tra',
      image: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400&h=300&fit=crop',
      price: 35000,
      discountPercent: 5,
      description: 'Trà đào cam sả tươi mát, hương vị tự nhiên.',
      rating: 4.7,
      reviews: 198,
      isBestSeller: false,
      isActive: true,
    },
    {
      name: 'Trà Ổi',
      categoryCode: 'tra',
      image: 'https://images.unsplash.com/photo-1597318113107-b7b4f5a8e2f4?w=400&h=300&fit=crop',
      price: 32000,
      discountPercent: 6,
      description: 'Trà ổi thơm ngon, giải nhiệt mùa hè.',
      rating: 4.4,
      reviews: 134,
      isBestSeller: false,
      isActive: true,
    },
    {
      name: 'Trà Chanh',
      categoryCode: 'tra',
      image: 'https://images.unsplash.com/photo-1571934811356-5cc061b6821f?w=400&h=300&fit=crop',
      price: 28000,
      discountPercent: 4,
      description: 'Trà chanh chua ngọt, tươi mát giải khát.',
      rating: 4.6,
      reviews: 167,
      isBestSeller: false,
      isActive: true,
    },
    {
      name: 'Trà Vải',
      categoryCode: 'tra',
      image: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=400&h=300&fit=crop',
      price: 36000,
      discountPercent: 8,
      description: 'Trà vải ngọt thanh, hương vị nhiệt đới.',
      rating: 4.5,
      reviews: 189,
      isBestSeller: false,
      isActive: true,
    },
    {
      name: 'Trà Sữa Trân Châu',
      categoryCode: 'tra_sua',
      image: 'https://images.unsplash.com/photo-1525385133512-2f3bdd039054?w=400&h=300&fit=crop',
      price: 40000,
      discountPercent: 8,
      description: 'Trà sữa trân châu đen ngọt ngào, đậm đà.',
      rating: 4.4,
      reviews: 312,
      isBestSeller: false,
      isActive: true,
    },
    {
      name: 'Trà Sữa Matcha',
      categoryCode: 'tra_sua',
      image: 'https://images.unsplash.com/photo-1571934811356-5cc061b6821f?w=400&h=300&fit=crop',
      price: 45000,
      discountPercent: 7,
      description: 'Trà sữa matcha thơm ngon, vị đắng nhẹ hài hòa.',
      rating: 4.9,
      reviews: 234,
      isBestSeller: false,
      isActive: true,
    },
    {
      name: 'Trà Sữa Thái',
      categoryCode: 'tra_sua',
      image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=300&fit=crop',
      price: 42000,
      discountPercent: 9,
      description: 'Trà sữa Thái đậm đà màu cam đặc trưng.',
      rating: 4.6,
      reviews: 198,
      isBestSeller: false,
      isActive: true,
    },
    {
      name: 'Trà Sữa Socola',
      categoryCode: 'tra_sua',
      image: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=400&h=300&fit=crop',
      price: 46000,
      discountPercent: 11,
      description: 'Trà sữa socola ngọt ngào cho người yêu chocolate.',
      rating: 4.5,
      reviews: 176,
      isBestSeller: false,
      isActive: true,
    },
    {
      name: 'Matcha Latte',
      categoryCode: 'special_drinks',
      image: 'https://images.unsplash.com/photo-1515823064-d6e0c04616a7?w=400&h=300&fit=crop',
      price: 48000,
      discountPercent: 12,
      description: 'Matcha latte Nhật Bản nguyên chất, vị đắng nhẹ.',
      rating: 4.8,
      reviews: 312,
      isBestSeller: false,
      isActive: true,
    },
    {
      name: 'Golden Milk Latte',
      categoryCode: 'special_drinks',
      image: 'https://images.unsplash.com/photo-1571115764595-644a1f56a55c?w=400&h=300&fit=crop',
      price: 52000,
      discountPercent: 8,
      description: 'Latte nghệ vàng bổ dưỡng, tốt cho sức khỏe.',
      rating: 4.3,
      reviews: 145,
      isBestSeller: false,
      isActive: true,
    },
    {
      name: 'Dirty Matcha',
      categoryCode: 'special_drinks',
      image: 'https://images.unsplash.com/photo-1497935586351-b67a49e012bf?w=400&h=300&fit=crop',
      price: 55000,
      discountPercent: 10,
      description: 'Matcha kết hợp espresso, độc đáo và thú vị.',
      rating: 4.7,
      reviews: 189,
      isBestSeller: false,
      isActive: true,
    },
    {
      name: 'Brown Sugar Latte',
      categoryCode: 'special_drinks',
      image: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=400&h=300&fit=crop',
      price: 50000,
      discountPercent: 9,
      description: 'Latte đường nâu thơm ngon, ngọt thanh tự nhiên.',
      rating: 4.6,
      reviews: 223,
      isBestSeller: false,
      isActive: true,
    },
    {
      name: 'Sinh Tố Bơ',
      categoryCode: 'nuoc_ep',
      image: 'https://images.unsplash.com/photo-1623065422902-4eb5af9c2b4c?w=400&h=300&fit=crop',
      price: 42000,
      discountPercent: 10,
      description: 'Sinh tố bơ béo ngậy, bổ dưỡng cho sức khỏe.',
      rating: 4.3,
      reviews: 167,
      isBestSeller: false,
      isActive: true,
    },
    {
      name: 'Nước Ép Cam',
      categoryCode: 'nuoc_ep',
      image: 'https://images.unsplash.com/photo-1621506289937-a8e4df240d0b?w=400&h=300&fit=crop',
      price: 28000,
      discountPercent: 5,
      description: 'Nước ép cam tươi, giàu vitamin C tự nhiên.',
      rating: 4.6,
      reviews: 198,
      isBestSeller: false,
      isActive: true,
    },
    {
      name: 'Sinh Tố Dâu',
      categoryCode: 'nuoc_ep',
      image: 'https://images.unsplash.com/photo-1553530979-33e94af1e83e?w=400&h=300&fit=crop',
      price: 38000,
      discountPercent: 8,
      description: 'Sinh tố dâu tươi ngọt ngào, màu sắc bắt mắt.',
      rating: 4.5,
      reviews: 156,
      isBestSeller: false,
      isActive: true,
    },
    {
      name: 'Nước Ép Táo',
      categoryCode: 'nuoc_ep',
      image: 'https://images.unsplash.com/photo-1570197788417-0e82375c9371?w=400&h=300&fit=crop',
      price: 30000,
      discountPercent: 6,
      description: 'Nước ép táo tươi mát, thanh lọc cơ thể.',
      rating: 4.4,
      reviews: 134,
      isBestSeller: false,
      isActive: true,
    },
    {
      name: 'Sinh Tố Xoài',
      categoryCode: 'nuoc_ep',
      image: 'https://images.unsplash.com/photo-1546173159-315724a31696?w=400&h=300&fit=crop',
      price: 40000,
      discountPercent: 7,
      description: 'Sinh tố xoài thơm ngon, vị ngọt nhiệt đới.',
      rating: 4.7,
      reviews: 189,
      isBestSeller: false,
      isActive: true,
    },
    {
      name: 'Coca Cola',
      categoryCode: 'nuoc_ngot',
      image: 'https://images.unsplash.com/photo-1581636625402-29b2a704ef13?w=400&h=300&fit=crop',
      price: 15000,
      discountPercent: 0,
      description: 'Coca Cola mát lạnh, sảng khoái.',
      rating: 4.5,
      reviews: 267,
      isBestSeller: false,
      isActive: true,
    },
    {
      name: 'Pepsi',
      categoryCode: 'nuoc_ngot',
      image: 'https://images.unsplash.com/photo-1629203851122-3726ecdf080e?w=400&h=300&fit=crop',
      price: 15000,
      discountPercent: 0,
      description: 'Pepsi cola tươi mát, giải khát hiệu quả.',
      rating: 4.3,
      reviews: 198,
      isBestSeller: false,
      isActive: true,
    },
    {
      name: 'Nước Suối',
      categoryCode: 'nuoc_ngot',
      image: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=400&h=300&fit=crop',
      price: 10000,
      discountPercent: 0,
      description: 'Nước suối tinh khiết, cần thiết cho cơ thể.',
      rating: 4.8,
      reviews: 456,
      isBestSeller: false,
      isActive: true,
    },
  ];

  for (const p of defaultProducts) {
    const categoryId = codeToId[p.categoryCode];
    if (!categoryId) {
      //   console.warn(`Category code ${p.categoryCode} not found for product ${p.name}`);
      continue;
    }
    const existing = await prisma.product.findFirst({
      where: { name: p.name, categoryId },
    });
    if (!existing) {
      await prisma.product.create({
        data: {
          name: p.name,
          categoryId,
          image: p.image,
          price: p.price,
          discountPercent: p.discountPercent ?? 0,
          description: p.description,
          rating: p.rating,
          reviews: p.reviews,
          isBestSeller: p.isBestSeller,
          isActive: p.isActive,
        },
      });
      //   console.log(`Product ${p.name} created.`);
    } else {
      //   console.log(`Product ${p.name} already exists.`);
    }
  }
}
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

export async function initializeCategory() {
  const defaultCategories = [
    { code: 'cafe_viet', name: 'Cafe Việt' },
    { code: 'cafe_may', name: 'Cafe Máy' },
    { code: 'cafe_da_xay', name: 'Cafe Đá Xay' },
    { code: 'tra', name: 'Trà' },
    { code: 'special_drinks', name: 'Special Drinks' },
    { code: 'nuoc_ep', name: 'Nước ép - Sinh tố' },
    { code: 'tra_sua', name: 'Trà Sữa' },
    { code: 'nuoc_ngot', name: 'Nước Ngọt - Giải Khát' },
  ];

  for (const category of defaultCategories) {
    const existing = await prisma.category.findFirst({
      where: { code: category.code },
    });
    if (!existing) {
      await prisma.category.create({ data: category });
      //   console.log(`Category ${category.name} created.`);
    } else {
      //   console.log(`Category ${category.name} already exists.`);
    }
  }
}
