openapi: 3.1.0
info:
  title: Prisma API
  description: ""
  version: 1.0.0
paths: {}
components:
  schemas:
    Category:
      type: object
      properties:
        id:
          type: integer
          format: int64
        code:
          type: string
        name:
          type: string
        products:
          type: array
          items:
            $ref: "#/components/schemas/Product"
      required:
        - id
        - code
        - name
        - products
    Product:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        category:
          $ref: "#/components/schemas/Category"
        categoryId:
          type: integer
          format: int64
        image:
          type: string
        price:
          type: integer
          format: int32
        discountPercent:
          type: integer
          format: int32
        description:
          type: string
        rating:
          type: number
          format: double
        reviews:
          type: integer
          format: int32
        isBestSeller:
          type: boolean
        isActive:
          type: boolean
      required:
        - id
        - name
        - category
        - categoryId
        - image
        - price
        - discountPercent
        - description
        - rating
        - reviews
        - isBestSeller
        - isActive
  responses: {}
  parameters: {}
  examples: {}
  requestBodies: {}
  headers: {}
  securitySchemes: {}
  links: {}
  callbacks: {}
tags: []
servers: []
